FROM INSERT_YOUR_REGISTRY/tf-gdal:latest

COPY requirements.txt .

# Install other requirements
RUN pip install -r requirements.txt

CMD [ "echo", "You should add your code and change this command!" ]
